# Server config
server.port=8700
server.servlet.context-path=/user

# Spring application
spring.application.name=user-service

# Datasource
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-user:5432/ms_user}
spring.datasource.username=${DB_USER:ms}
spring.datasource.password=${DB_PASS:ms}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Cache Redis
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# Config Server
spring.config.import=optional:configserver:http://config-server:9296

# Eureka
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

# Zipkin tracing
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# Resource server JWT config
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://identity-service:9100/identity/.well-known/jwks.json
