# Server configuration
server.port=8800
server.servlet.context-path=/order

# Spring application name
spring.application.name=order-service

# Database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-order:5432/ms_order}
spring.datasource.username=${DB_USER:ms}
spring.datasource.password=${DB_PASS:ms}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BROKER:kafka:9092}
# Kafka producer serialization
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# External config server
spring.config.import=optional:configserver:http://config-server:9296

# Eureka configuration
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

# Zipkin tracing endpoint
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://identity-service/identity/.well-known/jwks.json

spring.profiles.active=dev
logging.level.org.axonframework=DEBUG

axon.axonserver.enabled=false
axon.serializer.general=jackson
axon.serializer.events=jackson
axon.serializer.messages=jackson
