server:
  port: 8802
  servlet:
    context-path: /shipping

spring:
  application:
    name: shipping-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity-service/identity/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://postgres-shipping:5432/ms_shipping
    username: ms
    password: ms
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://mongo-shipping:27017/ms_shipping

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: shipping-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans



axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson

logging:
  level:
    root: INFO
    org.axonframework: DEBUG
    com.microshop.shippingservice: DEBUG
