server.port=8900
server.servlet.context-path=/payment

spring.application.name=payment-service

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-payment:5432/ms_payment}
spring.datasource.username=${DB_USER:ms}
spring.datasource.password=${DB_PASS:ms}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.kafka.bootstrap-servers=${KAFKA_BROKER:kafka:9092}

# ========== KAFKA CONSUMER CONFIG ==========
spring.kafka.consumer.group-id=payment-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.microshop.paymentservice.dto.event.OrderPlacedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.microshop.paymentservice.dto.event
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.listener.ack-mode=record
spring.kafka.listener.missing-topics-fatal=false

#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.config.import=optional:configserver:http://config-server:9296

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://identity-service/identity/.well-known/jwks.json

