server.port=8900
server.servlet.context-path=/payment

spring.application.name=payment-service

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres-payment:5432/ms_payment}
spring.datasource.username=${DB_USER:ms}
spring.datasource.password=${DB_PASS:ms}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.kafka.bootstrap-servers=${KAFKA_BROKER:kafka:9092}

spring.config.import=optional:configserver:http://config-server:9296

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://identity-service/identity/.well-known/jwks.json
