# Server configuration
server.port=8600
server.servlet.context-path=/product

# Application name
spring.application.name=product-service

# MongoDB configuration
spring.data.mongodb.uri=${MONGO_URL:mongodb://mongo-product:27017/microshop_product}

# Elasticsearch configuration
spring.elasticsearch.uris=${ES_URIS:http://microshop-elasticsearch:9200}
spring.elasticsearch.connection-timeout=5s
spring.elasticsearch.socket-timeout=30s

# Jackson configuration
spring.jackson.serialization.write-dates-as-timestamps=false

# Import config server
spring.config.import=optional:configserver:http://config-server:9296

# Eureka configuration
eureka.client.service-url.defaultZone=http://microshop-discovery:8761/eureka


# Zipkin tracing
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# OAuth2 Resource Server (JWKS from identity-service)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://identity-service/identity/.well-known/jwks.json


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
