server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka