server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: shipping-service
          uri: lb://shipping-service
          predicates:
            - Path=/shipping/**
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka