server.port=9296
spring.application.name=config-server

spring.profiles.active=native

# Ch? ??nh th? m?c ch?a file c?u hình (?ã ???c mount t? docker-compose)
spring.cloud.config.server.native.search-locations=file:/config-repo
